using System.Text.Json.Serialization;

namespace GeminiDotnet.ContentGeneration;

[JsonConverter(typeof(JsonStringEnumConverter<FinishReason>))]
public enum FinishReason
{
    /// <summary>
    /// Default value. This value is unused.
    /// </summary>
    [JsonStringEnumMemberName("FINISH_REASON_UNSPECIFIED")]
    Unspecified,

    /// <summary>
    /// Natural stop point of the model or provided stop sequence.
    /// </summary>
    [JsonStringEnumMemberName("STOP")]
    Stop,

    /// <summary>
    /// The maximum number of tokens as specified in the request was reached.
    /// </summary>
    [JsonStringEnumMemberName("MAX_TOKENS")]
    MaxTokens,

    /// <summary>
    /// The response candidate content was flagged for safety reasons.
    /// </summary>
    [JsonStringEnumMemberName("SAFETY")]
    Safety,

    /// <summary>
    /// The response candidate content was flagged for recitation reasons.
    /// </summary>
    [JsonStringEnumMemberName("RECITATION")]
    Recitation,

    /// <summary>
    /// The response candidate content was flagged for using an unsupported language.
    /// </summary>
    [JsonStringEnumMemberName("LANGUAGE")]
    Language,

    /// <summary>
    /// Unknown reason.
    /// </summary>
    [JsonStringEnumMemberName("OTHER")]
    Other,

    /// <summary>
    /// Token generation stopped because the content contains forbidden terms.
    /// </summary>
    [JsonStringEnumMemberName("BLOCKLIST")]
    Blocklist,

    /// <summary>
    /// Token generation stopped for potentially containing prohibited content.
    /// </summary>
    [JsonStringEnumMemberName("PROHIBITED_CONTENT")]
    ProhibitedContent,

    /// <summary>
    /// Token generation stopped because the content potentially contains Sensitive Personally Identifiable Information (SPII).
    /// </summary>
    [JsonStringEnumMemberName("SPII")]
    SPII,

    /// <summary>
    /// The function call generated by the model is invalid.
    /// </summary>
    [JsonStringEnumMemberName("MALFORMED_FUNCTION_CALL")]
    MalformedFunctionCall,

    /// <summary>
    /// Token generation stopped because generated images contain safety violations.
    /// </summary>
    [JsonStringEnumMemberName("IMAGE_SAFETY")]
    ImageSafety,

    /// <summary>
    /// Model generated a tool call but no tools were enabled in the request.
    /// </summary>
    [JsonStringEnumMemberName("UNEXPECTED_TOOL_CALL")]
    UnexpectedToolCall,

    /// <summary>
    /// Model called too many tools consecutively, thus the system exited execution.
    /// </summary>
    [JsonStringEnumMemberName("TOO_MANY_TOOL_CALLS")]
    TooManyToolCalls
}
