using System.Text.Json.Serialization;

namespace GeminiDotnet;

// Proto3 JSON encoding represents 64-bit integer values (int64, uint64, etc.) as
// strings to avoid precision loss in IEEE 754 floats. 32-bit integers are unaffected
// but AllowReadingFromString is harmless for them and doesn't change write behavior.
[JsonSourceGenerationOptions(WriteIndented = false, NumberHandling = JsonNumberHandling.AllowReadingFromString)]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.ListOperationsResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Operation))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Empty))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Batches.EmbedContentBatch))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Batches.GenerateContentBatch))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.CachedContents.ListCachedContentsResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.CachedContents.CachedContent))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Corpora.ListCorporaResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Corpora.Corpus))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.ListPermissionsResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Permission))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.GenerateContentRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.GenerateContentResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Files.ListFilesResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Files.CreateFileRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Files.CreateFileResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.FilesRegister.RegisterFilesRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.FilesRegister.RegisterFilesResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Files.File))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Files.DownloadFileResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.FileSearchStores.ListFileSearchStoresResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.FileSearchStores.FileSearchStore))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.FileSearchStores.ImportFileRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.FileSearchStores.ImportFileOperation))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.FileSearchStores.UploadToFileSearchStoreRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.FileSearchStores.UploadToFileSearchStoreOperation))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.FileSearchStores.ListDocumentsResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.FileSearchStores.Document))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.GeneratedFiles.ListGeneratedFilesResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.GeneratedFiles.GeneratedFile))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.ListModelsResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.Model))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.AsyncBatchEmbedContentRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.AsyncBatchEmbedContentOperation))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.BatchEmbedContentsRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.BatchEmbedContentsResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.BatchEmbedTextRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.BatchEmbedTextResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.BatchGenerateContentRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.BatchGenerateContentOperation))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.CountMessageTokensRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.CountMessageTokensResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.CountTextTokensRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.CountTextTokensResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.CountTokensRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.CountTokensResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.EmbedContentRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.EmbedContentResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.EmbedTextRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.EmbedTextResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.GenerateAnswerRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.GenerateAnswerResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.GenerateMessageRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.GenerateMessageResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.GenerateTextRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.GenerateTextResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.PredictRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.PredictResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.PredictLongRunningRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.Models.PredictLongRunningOperation))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.TunedModels.ListTunedModelsResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.TunedModels.TunedModel))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.TunedModels.CreateTunedModelOperation))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.TunedModels.TransferOwnershipRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1Beta.TunedModels.TransferOwnershipResponse))]
internal partial class V1BetaJsonContext : JsonSerializerContext;
