using System.Text.Json.Serialization;

namespace GeminiDotnet;

// Proto3 JSON encoding represents 64-bit integer values (int64, uint64, etc.) as
// strings to avoid precision loss in IEEE 754 floats. 32-bit integers are unaffected
// but AllowReadingFromString is harmless for them and doesn't change write behavior.
[JsonSourceGenerationOptions(WriteIndented = false, NumberHandling = JsonNumberHandling.AllowReadingFromString)]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.ListOperationsResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.Operation))]
[JsonSerializable(typeof(GeminiDotnet.V1.Empty))]
[JsonSerializable(typeof(GeminiDotnet.V1.EmbedContentBatch))]
[JsonSerializable(typeof(GeminiDotnet.V1.GenerateContentBatch))]
[JsonSerializable(typeof(GeminiDotnet.V1.GenerateContentRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1.GenerateContentResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.Files.ListFilesResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.Files.CreateFileRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1.Files.CreateFileResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.FilesRegister.RegisterFilesRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1.FilesRegister.RegisterFilesResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.Files.File))]
[JsonSerializable(typeof(GeminiDotnet.V1.Files.DownloadFileResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.FileSearchStores.ListFileSearchStoresResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.FileSearchStores.FileSearchStore))]
[JsonSerializable(typeof(GeminiDotnet.V1.FileSearchStores.ImportFileRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1.FileSearchStores.ImportFileOperation))]
[JsonSerializable(typeof(GeminiDotnet.V1.FileSearchStores.UploadToFileSearchStoreRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1.FileSearchStores.UploadToFileSearchStoreOperation))]
[JsonSerializable(typeof(GeminiDotnet.V1.FileSearchStores.ListDocumentsResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.FileSearchStores.Document))]
[JsonSerializable(typeof(GeminiDotnet.V1.FileSearchStores.DownloadMediaResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.Models.ListModelsResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.Models.Model))]
[JsonSerializable(typeof(GeminiDotnet.V1.AsyncBatchEmbedContentRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1.AsyncBatchEmbedContentOperation))]
[JsonSerializable(typeof(GeminiDotnet.V1.Models.BatchEmbedContentsRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1.Models.BatchEmbedContentsResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.BatchGenerateContentRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1.BatchGenerateContentOperation))]
[JsonSerializable(typeof(GeminiDotnet.V1.Models.CountTokensRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1.Models.CountTokensResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.EmbedContentRequest))]
[JsonSerializable(typeof(GeminiDotnet.V1.EmbedContentResponse))]
[JsonSerializable(typeof(GeminiDotnet.V1.TunedModels.CancelOperationRequest))]
internal partial class V1JsonContext : JsonSerializerContext;
