namespace GeminiDotnet.ContentGeneration.FunctionCalling;

/// <summary>
/// A <see cref="Tool"/> that executes code generated by the model, and automatically returns the result to the model.
/// See also <see cref="ExecutableCode"/> and <see cref="CodeExecutionResult"/> which are only generated when using this tool.
/// </summary>
/// <remarks>
/// This type has no fields.
/// </remarks>
public sealed record CodeExecution;
