namespace GeminiDotnet.ContentGeneration.FunctionCalling;

/// <summary>
/// A <see cref="Tool"/> that executes code generated by the model, and automatically returns the result to the model.
/// </summary>
public sealed record CodeExecution;
