namespace GeminiDotnet.V1;

/// <summary>
/// Tool that executes code generated by the model, and automatically returns
/// the result to the model.
/// See also <see cref="V1.ExecutableCode"/> and <see cref="V1.CodeExecutionResult"/> which are only generated
/// when using this tool.
/// </summary>
public sealed record CodeExecution
{
}

