using System.Text.Json.Serialization;

namespace GeminiDotnet.V1;

/// <summary>
/// Code generated by the model that is meant to be executed, and the result
/// returned to the model.
/// Only generated when using the <see cref="V1.CodeExecution"/> tool, in which the code will
/// be automatically executed, and a corresponding <see cref="V1.CodeExecutionResult"/> will
/// also be generated.
/// </summary>
public sealed record ExecutableCode
{
    /// <summary>
    /// Required. The code to be executed.
    /// </summary>
    [JsonPropertyName("code")]
    public required string Code { get; init; }

    /// <summary>
    /// Optional. Unique identifier of the <see cref="V1.ExecutableCode"/> part.
    /// The server returns the <see cref="V1.CodeExecutionResult"/> with the matching <see cref="Id"/>.
    /// </summary>
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public string? Id { get; init; }

    /// <summary>
    /// Required. Programming language of the <see cref="Code"/>.
    /// </summary>
    [JsonPropertyName("language")]
    public required ExecutableCodeLanguage Language { get; init; }
}

