using System.Text.Json.Serialization;

namespace GeminiDotnet.V1Beta.Models;

/// <summary>
/// Optional. Output only. The reason why the model stopped generating tokens.
/// If empty, the model has not stopped generating tokens.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<CandidateFinishReason>))]
public enum CandidateFinishReason
{
    /// <summary>
    /// Default value. This value is unused.
    /// </summary>
    [JsonStringEnumMemberName("FINISH_REASON_UNSPECIFIED")]
    Unspecified,

    /// <summary>
    /// Natural stop point of the model or provided stop sequence.
    /// </summary>
    [JsonStringEnumMemberName("STOP")]
    Stop,

    /// <summary>
    /// The maximum number of tokens as specified in the request was reached.
    /// </summary>
    [JsonStringEnumMemberName("MAX_TOKENS")]
    MaxTokens,

    /// <summary>
    /// The response candidate content was flagged for safety reasons.
    /// </summary>
    [JsonStringEnumMemberName("SAFETY")]
    Safety,

    /// <summary>
    /// The response candidate content was flagged for recitation reasons.
    /// </summary>
    [JsonStringEnumMemberName("RECITATION")]
    Recitation,

    /// <summary>
    /// The response candidate content was flagged for using an unsupported
    /// language.
    /// </summary>
    [JsonStringEnumMemberName("LANGUAGE")]
    Language,

    /// <summary>
    /// Unknown reason.
    /// </summary>
    [JsonStringEnumMemberName("OTHER")]
    Other,

    /// <summary>
    /// Token generation stopped because the content contains forbidden terms.
    /// </summary>
    [JsonStringEnumMemberName("BLOCKLIST")]
    Blocklist,

    /// <summary>
    /// Token generation stopped for potentially containing prohibited content.
    /// </summary>
    [JsonStringEnumMemberName("PROHIBITED_CONTENT")]
    ProhibitedContent,

    /// <summary>
    /// Token generation stopped because the content potentially contains
    /// Sensitive Personally Identifiable Information (SPII).
    /// </summary>
    [JsonStringEnumMemberName("SPII")]
    Spii,

    /// <summary>
    /// The function call generated by the model is invalid.
    /// </summary>
    [JsonStringEnumMemberName("MALFORMED_FUNCTION_CALL")]
    MalformedFunctionCall,

    /// <summary>
    /// Token generation stopped because generated images contain safety
    /// violations.
    /// </summary>
    [JsonStringEnumMemberName("IMAGE_SAFETY")]
    ImageSafety,

    /// <summary>
    /// Image generation stopped because generated images has other prohibited
    /// content.
    /// </summary>
    [JsonStringEnumMemberName("IMAGE_PROHIBITED_CONTENT")]
    ImageProhibitedContent,

    /// <summary>
    /// Image generation stopped because of other miscellaneous issue.
    /// </summary>
    [JsonStringEnumMemberName("IMAGE_OTHER")]
    ImageOther,

    /// <summary>
    /// The model was expected to generate an image, but none was generated.
    /// </summary>
    [JsonStringEnumMemberName("NO_IMAGE")]
    NoImage,

    /// <summary>
    /// Image generation stopped due to recitation.
    /// </summary>
    [JsonStringEnumMemberName("IMAGE_RECITATION")]
    ImageRecitation,

    /// <summary>
    /// Model generated a tool call but no tools were enabled in the request.
    /// </summary>
    [JsonStringEnumMemberName("UNEXPECTED_TOOL_CALL")]
    UnexpectedToolCall,

    /// <summary>
    /// Model called too many tools consecutively, thus the system exited
    /// execution.
    /// </summary>
    [JsonStringEnumMemberName("TOO_MANY_TOOL_CALLS")]
    TooManyToolCalls,

    /// <summary>
    /// Request has at least one thought signature missing.
    /// </summary>
    [JsonStringEnumMemberName("MISSING_THOUGHT_SIGNATURE")]
    MissingThoughtSignature,

    /// <summary>
    /// Finished due to malformed response.
    /// </summary>
    [JsonStringEnumMemberName("MALFORMED_RESPONSE")]
    MalformedResponse,
}

