using System.Text.Json.Serialization;

namespace GeminiDotnet.V1Beta.Files;

/// <summary>
/// Source of the File.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<FileSource>))]
public enum FileSource
{
    /// <summary>
    /// Used if source is not specified.
    /// </summary>
    [JsonStringEnumMemberName("SOURCE_UNSPECIFIED")]
    Unspecified,

    /// <summary>
    /// Indicates the file is uploaded by the user.
    /// </summary>
    [JsonStringEnumMemberName("UPLOADED")]
    Uploaded,

    /// <summary>
    /// Indicates the file is generated by Google.
    /// </summary>
    [JsonStringEnumMemberName("GENERATED")]
    Generated,

    /// <summary>
    /// Indicates the file is a registered, i.e. a Google Cloud Storage file.
    /// </summary>
    [JsonStringEnumMemberName("REGISTERED")]
    Registered,
}

