using System.Text.Json.Serialization;

namespace GeminiDotnet.V1Beta.FileSearchStores;

/// <summary>
/// Describes what the field reference contains.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<GdataMediaReferenceType>))]
public enum GdataMediaReferenceType
{
    /// <summary>
    /// Reference contains a GFS path or a local path.
    /// </summary>
    [JsonStringEnumMemberName("PATH")]
    Path,

    /// <summary>
    /// Reference points to a blobstore object. This could be either
    /// a v1 blob_ref or a v2 blobstore2_info. Clients should check
    /// blobstore2_info first, since v1 is being deprecated.
    /// </summary>
    [JsonStringEnumMemberName("BLOB_REF")]
    BlobRef,

    /// <summary>
    /// Data is included into this proto buffer
    /// </summary>
    [JsonStringEnumMemberName("INLINE")]
    Inline,

    /// <summary>
    /// Data should be accessed from the current service
    /// using the operation GetMedia.
    /// </summary>
    [JsonStringEnumMemberName("GET_MEDIA")]
    GetMedia,

    /// <summary>
    /// The content for this media object is stored across
    /// multiple partial media objects under the
    /// composite_media field.
    /// </summary>
    [JsonStringEnumMemberName("COMPOSITE_MEDIA")]
    CompositeMedia,

    /// <summary>
    /// Reference points to a bigstore object
    /// </summary>
    [JsonStringEnumMemberName("BIGSTORE_REF")]
    BigstoreRef,

    /// <summary>
    /// Indicates the data is stored in diff_version_response.
    /// </summary>
    [JsonStringEnumMemberName("DIFF_VERSION_RESPONSE")]
    DiffVersionResponse,

    /// <summary>
    /// Indicates the data is stored in diff_checksums_response.
    /// </summary>
    [JsonStringEnumMemberName("DIFF_CHECKSUMS_RESPONSE")]
    DiffChecksumsResponse,

    /// <summary>
    /// Indicates the data is stored in diff_download_response.
    /// </summary>
    [JsonStringEnumMemberName("DIFF_DOWNLOAD_RESPONSE")]
    DiffDownloadResponse,

    /// <summary>
    /// Indicates the data is stored in diff_upload_request.
    /// </summary>
    [JsonStringEnumMemberName("DIFF_UPLOAD_REQUEST")]
    DiffUploadRequest,

    /// <summary>
    /// Indicates the data is stored in diff_upload_response.
    /// </summary>
    [JsonStringEnumMemberName("DIFF_UPLOAD_RESPONSE")]
    DiffUploadResponse,

    /// <summary>
    /// Indicates the data is stored in cosmo_binary_reference.
    /// </summary>
    [JsonStringEnumMemberName("COSMO_BINARY_REFERENCE")]
    CosmoBinaryReference,

    /// <summary>
    /// Informs Scotty to generate a response payload with the size specified
    /// in the length field. The contents of the payload are generated by
    /// Scotty and are undefined. This is useful for testing download speeds
    /// between the user and Scotty without involving a real payload source.
    /// Note: range is not supported when using arbitrary_bytes.
    /// </summary>
    [JsonStringEnumMemberName("ARBITRARY_BYTES")]
    ArbitraryBytes,
}

