using System.Text.Json.Serialization;

namespace GeminiDotnet.V1Beta;

/// <summary>
/// Code generated by the model that is meant to be executed, and the result
/// returned to the model.
/// Only generated when using the <see cref="V1Beta.CachedContents.CodeExecution"/> tool, in which the code will
/// be automatically executed, and a corresponding <see cref="V1Beta.CodeExecutionResult"/> will
/// also be generated.
/// </summary>
public sealed record ExecutableCode
{
    /// <summary>
    /// Required. The code to be executed.
    /// </summary>
    [JsonPropertyName("code")]
    public required string Code { get; init; }

    /// <summary>
    /// Required. Programming language of the <see cref="Code"/>.
    /// </summary>
    [JsonPropertyName("language")]
    public required ExecutableCodeLanguage Language { get; init; }
}

